name: GitHub CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  gcc_10:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: bash tools/gha_gcc.sh
  clang_14:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: bash tools/gha_clang.sh
  msvc_2022:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          # See: https://github.com/conda-incubator/setup-miniconda?tab=readme-ov-file#example-14-remove-defaults-channel
          conda-remove-defaults: "true"
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Build
        shell: pwsh
        run: |
          conda install -y cmake
          mkdir build
          cd build
          cmake ../ -G "Visual Studio 17 2022" -A x64 -DIGOR_BUILD_TESTS=yes
          cmake --build . --config Debug -j2
          ctest -j4 -V -C Debug
  clang_tidy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: bash tools/gha_clang_tidy.sh
